var RESOURCE_DATA = {
  links: [
    { t: 'Follow up Refund Sheet', d: 'For customers that are reporting that refunds marked as successful have not been received after 10 business days. For refunds showing as failed, retry processing after an hour. If the refund fails again, please track the issue.', u: 'https://docs.google.com/spreadsheets/d/1e93ydbpPOt_ucH8DabDwfa65AqheLpcXAysfgfdVVYA/edit?gid=155669863#gid=155669863' },
    { t: 'CSR Manual Creation Tracker', d: 'This escalation sheet is used to document and track all brands that require manual order creation or reshipment requests.', u: 'https://docs.google.com/spreadsheets/d/1nsEKMBc34_QiHxorGuJOv6B34-3m8CEgNokPlVZaAag/edit?gid=1414496553#gid=1414496553' },
    { t: 'DHL Reshipment Claim Sheet', d: 'This escalation sheet is used as a tracker to log customer-reported tracking or packing issues—such as lost or delayed shipments, incorrect delivery, damaged items, incomplete orders, or wrong items—so the warehouse team can quickly investigate and resolve them', u: 'https://docs.google.com/spreadsheets/d/1Puj4kVn4hxKTCCKHU79wtPUc9kF879Z-/edit?pli=1&gid=1626765804#gid=1626765804' },
    { t: 'Marketing Email Tracker', d: 'These emails must be responded to as required, must not be closed or merged, and should always be assigned to Mary Rose Panti for tracking and monitoring.', u: 'https://docs.google.com/spreadsheets/d/19EqtioMwsh-uE0GcaZyXgQ7KoUa4YJbazdkYSq6ZnnI/edit?usp=sharing' },
    { t: 'Shopify Refund Sheet', d: 'This escalation sheet is used to track Shopify Refund Requests & Follow Ups. Orders should be escalated for refund if they cannot be found in Sticky but are created in Shiphero. If the order does not appear under the customer’s email, search using the customer’s name or any other available details. All possible search methods must be exhausted before proceeding with escalation.', u: 'https://docs.google.com/spreadsheets/d/1_tsC9xyqbQvMILQ0zHcCiQGEcGUy-AOlvjxB3FwPfYA/edit?gid=0#gid=0' },
    { t: 'Amazon | Walmart | Ebay Sheet', d: 'This escalation sheet is used to track Amazon, Walmart, and eBay inquiries for orders that were placed directly through these marketplaces and requesting proper review and follow-up.', u: 'https://docs.google.com/spreadsheets/d/1_tsC9xyqbQvMILQ0zHcCiQGEcGUy-AOlvjxB3FwPfYA/edit?gid=0#gid=0' },
    { t: 'OHA Refund Pushback Tagging', d: 'This escalation sheet is used for OHA Refund Push Back Tagging on OHA orders where Save and Upgrade offers have already been made and require proper tagging and follow-up.', u: 'https://docs.google.com/spreadsheets/d/10Pas0kcWf7uM5IJInfUGz0Ry8fSlMPdRhN8iw__Zajg/edit?usp=sharing' },
    { t: 'OHA Hearing Specialist Referrals / Consultation Portal', d: 'This escalation sheet is used for OHA Refund Push Back Tagging on OHA orders where Save and Upgrade offers have already been made and require proper tagging and follow-up.', u: 'https://specialist-training-portal.vercel.app/portal' },
    { t: 'NEW Undelivered Message Escalation', d: 'This escalation sheet is used to track and manage email messages that failed to send or were returned as undeliverable, ensuring timely investigation and resolution of delivery issues.', u: 'https://docs.google.com/spreadsheets/d/1qHKkhldX64HF81brktLcfHY6RCIAr7XQwAdvhbjWxU0/edit?gid=925490607#gid=925490607' },
    { t: 'Return Label Request for  Customers without valid email (socmed)', d: 'This escalation sheet is used to document and track return label requests for customers who cannot receive emails, ensuring their return labels are sent through Facebook Messenger when email delivery is not possible. This helps maintain a seamless, reliable, and well-tracked alternative communication method.', u: 'https://docs.google.com/spreadsheets/d/1_IKymCZEXIC9OMNJPvUUkPd5SYakB_z-YozLAXbQmEY/edit?gid=0#gid=0' },
    { t: 'Request Follow-up Escalation Sheet', d: 'Use this tracking sheet to escalate customers who call to follow up on an email response regarding their return request. Logging these cases enables coordination with the Email Team and allows us to request priority handling for customers awaiting a response.', u: 'https://docs.google.com/spreadsheets/d/1g6qqyLzbwPFD482kW_YbYEOacj05eJuVrQS5ddpr338/edit?gid=0#gid=0' },
    { t: 'Shopify CX Details Updating Sheet', d: 'Use this link to escalate customer requests for updating their name, email address, or phone number. Before escalating, make sure the customer’s details have been updated in both Sticky and ShipHero so the information remains consistent across systems.', u: 'https://docs.google.com/spreadsheets/d/10JTg3sfpzXYDfRkm079BU0vUL7bZPcmE6lwY3pp6hJ4/edit?gid=0#gid=0' },
    { t: 'Outbound Sales', d: 'This escalation sheet is used for customers requesting to place an order through phone call', u: 'https://docs.google.com/spreadsheets/d/11R-CosEoediUOVnUIHj2uI_2lKv9syOnNaBtLaIjr9Q/edit?gid=316129417#gid=316129417' }
  ],
  guides: [],
  contacts: []
};